name: publish
on:
  push:
    tags:
      # major.minor.patch - terraform version
      # a[0-9]+ - package version
      - '[0-9]+.[0-9]+.[0-9]+-a[0-9]+'

jobs:
  release-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.9"
      - name: build release distributions
        run: |
          python -m pip install -r requirements.txt
          python make_wheels.py
        env:
          GIT_TAG: "${{ github.ref_name }}"
      - name: upload windows dists
        uses: actions/upload-artifact@v4
        with:
          name: release-dists
          path: build/*.whl

  publish:
    runs-on: ubuntu-latest
    needs:
      - release-build
    permissions:
      id-token: write
    environment: release
    concurrency:
      group: publish
      cancel-in-progress: false
    steps:
      - name: Retrieve release distributions
        uses: actions/download-artifact@v4
        with:
          name: release-dists
          path: build/
      - name: Publish release distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          packages-dir: build/
          skip-existing: true
